map_server:
    ros__parameters:
        frame_id: map   
        topic_name: /map
        use_sim_time: false
        yaml_filename: "/home/yakir/bgu_cogniteam_social_navigation_ws/src/social_navigation_ui/map.yaml"